name: Build AMI

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    build-ami:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build AMI
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer
          pwd
          cd packer
          packer init .
          packer validate .
          packer build -var aws_access_key=$AWS_DEV_ACCESS_KEY -var aws_secret_key=$AWS_DEV_SECRET_KEY -var subnet_id=$AWS_DEV_SUBNET_ID -var aws_region=$AWS_REGION ami.pkr.hcl
        env:
          AWS_DEV_ACCESS_KEY: ${{ secrets.AWS_GH_ACCESS_KEY }}
          AWS_DEV_SECRET_KEY: ${{ secrets.AWS_GH_ACCESS_VAL }}
          AWS_DEV_SUBNET_ID: ${{ secrets.AWS_GH_DEV_SUBNET_ID }} #subnet-04c72e4d3f4a340ac
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_AMI: ${{ secrets.AWS_JENKINS_SOURCE_AMI }} #ami-053b0d53c279acc90
          AWS_DEMO_ACCOUNT_ID: ${{ secrets.AWS_UK_DEMO_ACCOUNT_ID }} #545141298702


      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GH_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_GH_ACCESS_VAL }}
          aws-region: us-east-1

      
      # - name: Build AMI
      #   uses: hashicorp/packer@v1
      #   with:
      #     build_path: .
      #     template: packer/jenkins-ami.json
