name: Build AMI

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    build-ami:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GH_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_GH_ACCESS_VAL }}
          aws-region: us-east-1

      
      # - name: Build AMI
      #   uses: hashicorp/packer@v1
      #   with:
      #     build_path: .
      #     template: packer/jenkins-ami.json
